### ISSUE TITLE
License for this repo

### ISSUE THREAD

**Issue by yanivnizan** [dschuermann/billing-hack#1]
Hi Dominik,

We realized that one of the members of our open source community contributed a fix based on your code to the SOOMLA framework (github.com/soomla). Here is the pull request if you want to take a look. https://github.com/soomla/android-store/pull/29.

I looked up your repo in Github and there is no mention of a license so I'm contacting you to know if its ok to use your code or if we need to take it out.

Yaniv

**Comment by dschuermann** [comment]
It's Apache v2.
The changes are also done by Google at https://code.google.com/p/marketbilling/source/detail?r=7bc191a004483a1034b758e1df0bda062088d840

**Comment by yanivnizan** [comment]
ok, thanks!

—
Sent from Mailbox for iPad 
yaniv@soom.la | +972.52.73.93.089 | skype: yaniv_nizan | Co-Founder @ SOOMLA
